- id: '1776327465398'
  alias: Start timer on motion detected
  description: ''
  triggers:
  - trigger: state
    entity_id:
    - binary_sensor.motion_sensor_node_motion_sensor_alarm
    from:
    to:
    - 'on'
  conditions: []
  actions:
  - action: timer.start
    metadata: {}
    target:
      entity_id: timer.disarmtimer
    data:
      duration:
        hours: 0
        minutes: 0
        seconds: 30
  mode: single
- id: '1776329076297'
  alias: Start alarm when timer finishes
  description: ''
  triggers:
  - trigger: event
    event_data:
      entity_id: timer.disarmtimer
    event_type: timer.finished
  conditions: []
  actions:
  - action: siren.turn_on
    metadata: {}
    target:
      entity_id: siren.buzzer_buzzer_control
    data: {}
  - action: telegram_bot.send_message
    metadata: {}
    data:
      entity_id:
      - notify.home_security_alert_bot_mairo_trump
      title: Alert!
      message: Motion detected in your home!
  mode: single
- id: '1777998260451'
  alias: RFID Scan Handler
  description: ''
  triggers:
  - trigger: mqtt
    options:
      topic: home/nodes/3/scanned
  conditions:
  - condition: state
    entity_id: input_boolean.armed_disarmed
    state:
    - 'on'
  actions:
  - variables:
      scanned_id: '{{ trigger.payload_json.value | upper }}'
      valid_ids: '{{ states(''input_text.rfid_valid_ids'').split('','') }}'
  - action: notify.send_message
    metadata: {}
    target:
      entity_id: notify.rfid_reader_rfid_authenticated
    data:
      message: '{{ 2 if scanned_id in valid_ids else 1 }}'
  - if:
    - condition: template
      value_template: '{{ scanned_id in valid_ids }}'
    then:
    - action: input_boolean.turn_off
      metadata: {}
      target:
        entity_id: input_boolean.armed_disarmed
      data: {}
    - action: timer.cancel
      metadata: {}
      target:
        entity_id: timer.disarmtimer
      data: {}
  mode: single
- id: '1778148497275'
  alias: RFID arm system
  description: ''
  triggers:
  - trigger: mqtt
    options:
      topic: home/nodes/3/scanned
  conditions:
  - condition: state
    entity_id: input_boolean.armed_disarmed
    state:
    - 'off'
  actions:
  - variables:
      scanned_id: '{{ trigger.payload_json.value | upper }}'
      valid_ids: '{{ states(''input_text.rfid_valid_ids'').split('','') }}'
  - if:
    - condition: template
      value_template: '{{ scanned_id in valid_ids }}'
    then:
    - action: input_boolean.turn_on
      metadata: {}
      target:
        entity_id: input_boolean.armed_disarmed
      data: {}
  mode: single
- id: '1778266999836'
  alias: RFID offline
  description: ''
  triggers:
  - trigger: state
    entity_id:
    - binary_sensor.rfid_reader_rfid_heartbeat
    from:
    - 'on'
    to:
    - unavailable
    - 'off'
    - unknown
  conditions: []
  actions:
  - action: telegram_bot.send_message
    metadata: {}
    data:
      entity_id:
      - notify.home_security_alert_bot_mairo_trump
      title: Node offline
      message: Your RFID reader has gone offline.
  mode: single
- id: '1778267119053'
  alias: Motion sensor offline
  description: ''
  triggers:
  - trigger: state
    entity_id:
    - binary_sensor.motion_sensor_node_motion_sensor_heartbeat
    from:
    - 'on'
    to:
    - unavailable
    - 'off'
    - unknown
  conditions: []
  actions:
  - action: telegram_bot.send_message
    metadata: {}
    data:
      entity_id:
      - notify.home_security_alert_bot_mairo_trump
      title: Node offline
      message: Your motion sensor node has gone offline.
  mode: single
- id: '1778267192235'
  alias: Buzzer offline
  description: ''
  triggers:
  - trigger: state
    entity_id:
    - binary_sensor.buzzer_buzzer_heartbeat
    from:
    - 'on'
    to:
    - unavailable
    - 'off'
    - unknown
  conditions: []
  actions:
  - action: telegram_bot.send_message
    metadata: {}
    data:
      entity_id:
      - notify.home_security_alert_bot_mairo_trump
      title: Node offline
      message: Your buzzer node has gone offline.
  mode: single
- id: '1778275327108'
  alias: Gateway offline
  description: ''
  triggers:
  - trigger: state
    entity_id:
    - sensor.gateway_gateway_battery_level
    from:
    to:
    - unavailable
    - unknown
  conditions: []
  actions:
  - action: telegram_bot.send_message
    metadata: {}
    data:
      entity_id:
      - notify.home_security_alert_bot_mairo_trump
      title: Gateway offline!
      message: Your gateway has gone offline.
  mode: single
